language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "B2cXK9iow6FQYKNZhcW4MoMXKE6EsPiwfHRVdU0XGjH2qEXgIaNfMEdwklE/TlZkyGKDd60Wg3gP1YdaUNjDBWOp2w/wc+XB7NR/tdI8sBXs0momb3G71tDSKDWLNwcf5OStTOlfDrFuy6G/r98KOeQ93wZjSvB8XdBQiKejpOYNZp+3XgQ0vkSM0cI7uP6OVaG/S6tL/ij4Ah0MMvReAv0UUAtF1rVqWIzbh+rMjK6McuMvTL/8krkE5zJe5x06/AMtdpTVO7dRzVUFg7JLzGTetUW1MAT3GXRqz3DVZRGuQZldVDehxvrfPee1G0xMlG9hCjOuyE9ImQLnfE/87JdOJtT6lhWspGkif3dBRkhgmT4v93DXy6qFAHJf/brhiVBdn5o90QY99GnSS1hemKs3ifbvXBEuJCMbXOKat4BD6BeQTmZIyOzaQXzfcHBu8nAhYkPfztoE46mux0rA5bDLWOvp0cHHYr29MEVAnC9j6wGqG96iLCwFoneyOcBrpoBgL7gcLv9Vpakjt0kPbozqcZseUuCnHQ7VYp+WWa74oxdfhGNIARYrhP3GPLOFw2HG4pVHfOYpU+S3SFFFjL2eliSHNq8lQ9n3hiKu9tSXdtguuMggrUaBNE8THpJrkDEkmeQOSmtuwMm1xZTJ03zO7x1ggk/XbXNx9bRnFYI="
env:
  secure: "Rmsvk9OUqJQI0RM9t79rfAsfy6zN2NJIMabqAAVPqUSRBTu5LTbGt2MttAC2cWbTT0vCaDV5876tXRWVOu9MIuSaCs9jProuxeCmkw0HaAKSe8MXpci1j25yJcCFoGKzW3xJN5y5iUkXz1Gx05MluCwivOeJdH6oRWQ8xOKkSX/rx9J43CT7rLpB9/AFY/61H/xDv6asE1zZC23P1sSGtb6DcDjtthgO7xoqFQWTtaQkvHm5E55NUtZxze2Z2nVy+Jam7yNlGzXFiXLEFxxW5svORTobpiVWr/dNeCUOt6i/hZnQjPySYcGEHSBodiDVPqy4RANh8Vkmr6M21POPBXhuTFf+R/se7U1L2tqW28ZOr2Buj3DDnmA8IYE7+h20Anie+PI3tpeW1QgwGxtCjmjYgXcib6goSKdN6gzwKjBzILFe7j4vDuzdxW8HeacKjiin6lZtZdOl7hGvul9SZRivnhsTouqPrQiWh72DWwP6YSPIzqN8BwALQU2UkvG51BGxx6AFFXmovYleFHcX/47Wu5Heq4QQbaO3zjHxmT8y3MJK495Tz5AjxGsh76y1AOrAEucHbl8Cg8LtHtZbeInpcmQH8VzW+ZV49fsmGC6QmxL4vXyQlzPF4IlpTlI2dVR226LZUEdG9L4piPfdZlWzhgpSo6SHXoNDuVq5do4="
